version: "2.0"
services:
  frontend:
    build: ./frontend
    image: frontend
    ports:
      - "80:8000"
    volumes:
      - "./frontend/:/app"
  notes:
    build: ./backend/noteservice
    image: backend
    ports:
      - "8080:8080"
    volumes:
      - "./backend/noteservice/target:/app"
  notedb:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
