version: "2.0"
services:
  frontend:
    build: ./frontend
    ports:
      - "80:8000"
    volumes:
      - "./frontend/:/app"
  notes:
    build: ./backend/noteservice
    ports:
      - "8080:8080"
  notedb:
    image: postgres
    volumes:
      - note_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  note_db:
