angular
    .module('noteApp',
        [
            'ngRoute',
            'notes',
            'notebooks',
            'notebookNotes',
            'favorites',
            'sideMenu',
            'core'
        ]);